name: Create Minecraft Datapack+Resourcepack zip files
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Datapack
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'bingo-bongo-bong.zip'
          directory: 'datapack'
          exclusions: > 
            .gitkeep

      - name: Archive Resourcepack
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'bingo-bongo-bong-resources.zip'
          directory: 'resourcepack'
          exclusions: > 
            .gitkeep

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: latest
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          artifacts:
            datapack/bingo-bongo-bong.zip,
            resourcepack/bingo-bongo-bong-resources.zip
          token: ${{ secrets.GITHUB_TOKEN }}
