name: Create Minecraft Datapack zip file
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'bingo-bongo-bong.zip'
          exclusions: > 
            *.git*
            /*.vscode/*
            /*.github/*
            /*workspace/*
            /*utils/*
            docker-compose.yaml
            README.md

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: latest
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "bingo-bongo-bong.zip"
          token: ${{ secrets.GITHUB_TOKEN }}